import { Geist, Geist_Mono } from "next/font/google";
import Provider from './provider.js'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {console.log("layout chala provider use kr raha hai")}
        <Toaster />
        <Provider className="">
          {console.log("children are", children)}
          {children}
        </Provider>
        {/* {children} */}
      </body>
    </html>
  );
}
